import type { Metadata } from "next";
import {
  Bree_Serif,
} from "next/font/google";
import "./globals.css";

const glory = Bree_Serif({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-glory",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${glory.variable} antialiased h-screen`}>
        {children}
      </body>
    </html>
  );
}
